export const ProvisionerId = Object.freeze({
  VITE: 'VITE',
  NEXTJS: 'NEXTJS',
  ANDROID_NATIVE: 'ANDROID_NATIVE',
  FLUTTER: 'FLUTTER',
  NODE_BACKEND: 'NODE_BACKEND',
  PYTHON_BACKEND: 'PYTHON_BACKEND',
  CLI: 'CLI',
  RUST: 'RUST',
  GO: 'GO',
  DOTNET: 'DOTNET',
  IOS: 'IOS',
  MOCK: 'MOCK',
  BROKEN_TEST: 'BROKEN_TEST',
  UNSUPPORTED: 'UNSUPPORTED'
});

export const SupportStatus = Object.freeze({
  LIVE_SUPPORTED: 'LIVE_SUPPORTED',
  SUPPORTED_IF_TOOLCHAIN_AVAILABLE: 'SUPPORTED_IF_TOOLCHAIN_AVAILABLE',
  DETECTION_ONLY: 'DETECTION_ONLY',
  UNSUPPORTED: 'UNSUPPORTED'
});

export const ProvisioningStatus = Object.freeze({
  PASS: 'PASS',
  FAIL: 'FAIL',
  NOT_RUN: 'NOT_RUN',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  RECOVERY_REQUIRED: 'RECOVERY_REQUIRED'
});

export const ProvisioningStepKind = Object.freeze({
  PREPARE_WORKSPACE: 'PREPARE_WORKSPACE',
  TOOLCHAIN_DISCOVERY: 'TOOLCHAIN_DISCOVERY',
  GENERATE: 'GENERATE',
  VALIDATE: 'VALIDATE',
  SECRET_CHECK: 'SECRET_CHECK',
  GIT_BASELINE: 'GIT_BASELINE',
  STARTER_VERIFICATION: 'STARTER_VERIFICATION'
});

export const AppCategory = Object.freeze({
  WEB: 'WEB',
  MOBILE: 'MOBILE',
  BACKEND: 'BACKEND',
  DESKTOP: 'DESKTOP',
  CLI: 'CLI',
  FULL_STACK: 'FULL_STACK',
  MULTI_APP: 'MULTI_APP'
});

export const AppPlatform = Object.freeze({
  WEB: 'WEB',
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  CROSS_PLATFORM: 'CROSS_PLATFORM',
  SERVER: 'SERVER',
  DESKTOP: 'DESKTOP'
});

export const VersionPolicy = Object.freeze({
  CURRENT_SUPPORTED: 'CURRENT_SUPPORTED',
  PINNED: 'PINNED'
});

export const LifecycleComponentStatus = Object.freeze({
  PLANNED: 'PLANNED',
  PROVISIONING: 'PROVISIONING',
  PROVISIONED: 'PROVISIONED',
  FAILED: 'FAILED'
});
