export const ApplicationKind = Object.freeze({
  WEB_UI: 'WEB_UI',
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  BACKEND: 'BACKEND',
  CLI: 'CLI',
  DESKTOP: 'DESKTOP',
  GENERIC: 'GENERIC',
  UNKNOWN: 'UNKNOWN'
});

export const RuntimeAdapterName = Object.freeze({
  PLAYWRIGHT_WEB: 'PLAYWRIGHT_WEB',
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  BACKEND: 'BACKEND',
  CLI: 'CLI',
  DESKTOP: 'DESKTOP',
  GENERIC: 'GENERIC'
});

export const RuntimeStatus = Object.freeze({
  PASS: 'PASS',
  FAIL: 'FAIL',
  PARTIAL: 'PARTIAL',
  NOT_RUN: 'NOT_RUN',
  NOT_APPLICABLE: 'NOT_APPLICABLE'
});

export const ScenarioPriority = Object.freeze({
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
});

export const ViewportCategory = Object.freeze({
  DESKTOP: 'DESKTOP',
  MOBILE: 'MOBILE',
  TABLET: 'TABLET'
});

export const BaselineKind = Object.freeze({
  REFERENCE_APPROVED: 'REFERENCE_APPROVED',
  GENERATED_REFERENCE: 'GENERATED_REFERENCE',
  NO_BASELINE: 'NO_BASELINE'
});

export const RuntimeFindingCode = Object.freeze({
  RUNTIME_START_FAILED: 'RUNTIME_START_FAILED',
  RUNTIME_READINESS_TIMEOUT: 'RUNTIME_READINESS_TIMEOUT',
  RUNTIME_CRASH: 'RUNTIME_CRASH',
  RUNTIME_PROCESS_EXITED: 'RUNTIME_PROCESS_EXITED',
  SCENARIO_FAILED: 'SCENARIO_FAILED',
  BROWSER_ERROR: 'BROWSER_ERROR',
  NETWORK_FAILURE: 'NETWORK_FAILURE',
  ACCESSIBILITY_FAILURE: 'ACCESSIBILITY_FAILURE',
  SCREENSHOT_CAPTURE_FAILED: 'SCREENSHOT_CAPTURE_FAILED',
  VISUAL_REVIEW_FAILED: 'VISUAL_REVIEW_FAILED',
  VISUAL_BLOCKING_FINDING: 'VISUAL_BLOCKING_FINDING',
  DEVICE_BOOT_FAILED: 'DEVICE_BOOT_FAILED',
  APP_INSTALL_FAILED: 'APP_INSTALL_FAILED',
  APP_LAUNCH_FAILED: 'APP_LAUNCH_FAILED',
  EMULATOR_UNAVAILABLE: 'EMULATOR_UNAVAILABLE',
  IOS_RUNTIME_INFRASTRUCTURE_UNAVAILABLE: 'IOS_RUNTIME_INFRASTRUCTURE_UNAVAILABLE',
  ANDROID_RUNTIME_INFRASTRUCTURE_UNAVAILABLE: 'ANDROID_RUNTIME_INFRASTRUCTURE_UNAVAILABLE',
  STALE_RUNTIME_EVIDENCE: 'STALE_RUNTIME_EVIDENCE',
  MISSING_RUNTIME_TEST_CONFIGURATION: 'MISSING_RUNTIME_TEST_CONFIGURATION',
  INFRASTRUCTURE_UNAVAILABLE: 'INFRASTRUCTURE_UNAVAILABLE'
});

export const DEFAULT_VIEWPORTS = Object.freeze({
  DESKTOP: { name: ViewportCategory.DESKTOP, width: 1280, height: 800 },
  MOBILE: { name: ViewportCategory.MOBILE, width: 390, height: 844 },
  TABLET: { name: ViewportCategory.TABLET, width: 768, height: 1024 }
});

export const WEB_BROWSER_POLICY = Object.freeze({
  chromium: 'REQUIRED',
  firefox: 'OPTIONAL',
  webkit: 'OPTIONAL'
});
