import { redactSecrets as redactSecretText, redactDeep } from '../secrets/redact.js';

const SECRET_NAME = /api[_-]?key|token|secret|password|authorization|auth/i;

export const ErrorCode = Object.freeze({
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_FAILURE: 'PROVIDER_FAILURE',
  ALL_PROVIDERS_FAILED: 'ALL_PROVIDERS_FAILED',
  AUTH_FAILURE: 'AUTH_FAILURE',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  INSUFFICIENT_COUNCIL: 'INSUFFICIENT_COUNCIL',
  INVALID_SPECIFICATION: 'INVALID_SPECIFICATION',
  CHAIR_FAILURE: 'CHAIR_FAILURE',
  CURSOR_TIMEOUT: 'CURSOR_TIMEOUT',
  CURSOR_EXECUTION_FAILED: 'CURSOR_EXECUTION_FAILED',
  CURSOR_EXECUTABLE_UNAVAILABLE: 'CURSOR_EXECUTABLE_UNAVAILABLE',
  CURSOR_AUTH_FAILURE: 'CURSOR_AUTH_FAILURE',
  MOCK_BACKEND_NOT_ALLOWED: 'MOCK_BACKEND_NOT_ALLOWED',
  RECOVERY_FAILED: 'RECOVERY_FAILED',
  MAX_ITERATIONS_REACHED: 'MAX_ITERATIONS_REACHED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  COMPLETION_GATE_REJECTED: 'COMPLETION_GATE_REJECTED',
  RETRY_NOT_ELIGIBLE: 'RETRY_NOT_ELIGIBLE',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  JOB_LEASE_LOST: 'JOB_LEASE_LOST',
  JOB_DEAD_LETTERED: 'JOB_DEAD_LETTERED',
  WORKSPACE_UNSAFE: 'WORKSPACE_UNSAFE',
  GIT_POLICY_VIOLATION: 'GIT_POLICY_VIOLATION',
  CURSOR_PREFLIGHT_FAILED: 'CURSOR_PREFLIGHT_FAILED',
  SECRET_FILE_BLOCKED: 'SECRET_FILE_BLOCKED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  VERIFICATION_PREFLIGHT_FAILED: 'VERIFICATION_PREFLIGHT_FAILED',
  VERIFICATION_COMMAND_INVALID: 'VERIFICATION_COMMAND_INVALID',
  MISSING_PROJECT_CONFIGURATION: 'MISSING_PROJECT_CONFIGURATION',
  RUNTIME_START_FAILED: 'RUNTIME_START_FAILED',
  RUNTIME_READINESS_TIMEOUT: 'RUNTIME_READINESS_TIMEOUT',
  RUNTIME_CRASH: 'RUNTIME_CRASH',
  RUNTIME_PROCESS_EXITED: 'RUNTIME_PROCESS_EXITED',
  SCENARIO_FAILED: 'SCENARIO_FAILED',
  BROWSER_ERROR: 'BROWSER_ERROR',
  NETWORK_FAILURE: 'NETWORK_FAILURE',
  ACCESSIBILITY_FAILURE: 'ACCESSIBILITY_FAILURE',
  SCREENSHOT_CAPTURE_FAILED: 'SCREENSHOT_CAPTURE_FAILED',
  VISUAL_REVIEW_FAILED: 'VISUAL_REVIEW_FAILED',
  VISUAL_BLOCKING_FINDING: 'VISUAL_BLOCKING_FINDING',
  DEVICE_BOOT_FAILED: 'DEVICE_BOOT_FAILED',
  APP_INSTALL_FAILED: 'APP_INSTALL_FAILED',
  APP_LAUNCH_FAILED: 'APP_LAUNCH_FAILED',
  EMULATOR_UNAVAILABLE: 'EMULATOR_UNAVAILABLE',
  IOS_RUNTIME_INFRASTRUCTURE_UNAVAILABLE: 'IOS_RUNTIME_INFRASTRUCTURE_UNAVAILABLE',
  STALE_RUNTIME_EVIDENCE: 'STALE_RUNTIME_EVIDENCE',
  MISSING_RUNTIME_TEST_CONFIGURATION: 'MISSING_RUNTIME_TEST_CONFIGURATION',
  VISION_UNSUPPORTED: 'VISION_UNSUPPORTED',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',
  PROVISIONING_PLAN_INVALID: 'PROVISIONING_PLAN_INVALID',
  PROVISIONING_IDENTITY_INVALID: 'PROVISIONING_IDENTITY_INVALID',
  PROVISIONING_VALIDATION_FAILED: 'PROVISIONING_VALIDATION_FAILED',
  PROVISIONING_COMMAND_INVALID: 'PROVISIONING_COMMAND_INVALID',
  PROVISIONING_UNSUPPORTED: 'PROVISIONING_UNSUPPORTED',
  PROVISIONING_INFRASTRUCTURE_UNAVAILABLE: 'PROVISIONING_INFRASTRUCTURE_UNAVAILABLE',
  PROVISIONING_STARTER_INVALID: 'PROVISIONING_STARTER_INVALID',
  IOS_PROVISIONING_UNAVAILABLE: 'IOS_PROVISIONING_UNAVAILABLE',
  SANDBOX_INFRASTRUCTURE_UNAVAILABLE: 'SANDBOX_INFRASTRUCTURE_UNAVAILABLE',
  SANDBOX_VIOLATION: 'SANDBOX_VIOLATION',
  SANDBOX_RESOURCE_LIMIT: 'SANDBOX_RESOURCE_LIMIT',
  SECRET_ACCESS_DENIED: 'SECRET_ACCESS_DENIED',
  AUTHZ_DENIED: 'AUTHZ_DENIED',
  SECRET_DETECTED_IN_SOURCE: 'SECRET_DETECTED_IN_SOURCE',
  NETWORK_POLICY_DENIED: 'NETWORK_POLICY_DENIED',
  DELIVERY_PREPARATION_FAILED: 'DELIVERY_PREPARATION_FAILED',
  DELIVERY_LINEAGE_INVALID: 'DELIVERY_LINEAGE_INVALID',
  STALE_DELIVERY: 'STALE_DELIVERY',
  OWNER_DECISION_CONFLICT: 'OWNER_DECISION_CONFLICT',
  INVALID_OWNER_FEEDBACK: 'INVALID_OWNER_FEEDBACK'
});

export function redactSecrets(value) {
  return redactSecretText(value);
}

export function sanitizeDetails(details) {
  if (!details || typeof details !== 'object' || Array.isArray(details)) return {};
  const out = {};
  for (const [key, value] of Object.entries(details)) {
    if (SECRET_NAME.test(key)) out[key] = '[redacted]';
    else if (typeof value === 'string') out[key] = redactSecrets(value);
    else if (value && typeof value === 'object') out[key] = redactDeep(value);
    else out[key] = value;
  }
  return out;
}

export class PlatformError extends Error {
  constructor({ code, message, phase = null, retryable = true, details = {} }) {
    super(redactSecrets(message || code));
    this.name = 'PlatformError';
    this.code = code || ErrorCode.UNEXPECTED_ERROR;
    this.phase = phase;
    this.retryable = retryable !== false;
    this.details = sanitizeDetails(details);
    this.at = new Date().toISOString();
  }

  toRecord() {
    return {
      code: this.code,
      message: this.message,
      phase: this.phase,
      retryable: this.retryable,
      at: this.at,
      details: this.details
    };
  }
}

export function toErrorRecord(error, phase = null) {
  if (error instanceof PlatformError) {
    const record = error.toRecord();
    if (phase && !record.phase) record.phase = phase;
    return record;
  }
  const code = typeof error?.code === 'string' && Object.values(ErrorCode).includes(error.code)
    ? error.code
    : ErrorCode.UNEXPECTED_ERROR;
  return {
    code,
    message: redactSecrets(error?.message || String(error)),
    phase: phase || error?.phase || null,
    retryable: error?.retryable !== false,
    at: new Date().toISOString(),
    details: sanitizeDetails(error?.details || {})
  };
}

export function isTimeoutError(error) {
  return error?.name === 'TimeoutError' || error?.name === 'AbortError' || error?.code === ErrorCode.PROVIDER_TIMEOUT || error?.code === ErrorCode.CURSOR_TIMEOUT;
}
