import fs from 'node:fs/promises';
import path from 'node:path';
import { specProductName } from '../orchestrator/gate.js';

export const DEMO_APP_DISCLAIMER = 'This application was generated by the ADP demo using MOCK Council/Cursor execution. It is intended to demonstrate the owner workflow and is not a production-verified build.';

const RECIPE_JOURNEYS = [
  'Browse the available recipes.',
  'Search for a recipe.',
  'Open recipe details.',
  'Save a recipe to Favorites.',
  'Add a recipe to the weekly meal plan.'
];

const GENERIC_JOURNEYS = [
  'Browse the available items.',
  'Search or filter the catalog.',
  'Open an item to view details.',
  'Save an item to Favorites.',
  'Add an item to this week\'s plan.'
];

export function isDemoDelivery(project) {
  return Boolean(project?.demo);
}

export function isRecipeFixture(project) {
  const text = `${project?.idea || ''} ${specProductName(project?.council?.discovery?.spec) || ''}`.toLowerCase();
  return /\brecipe|\bmeal plan/.test(text);
}

export function lastOwnerFeedback(project) {
  return (project?.ownerReviews || []).filter(item => item.decision === 'CHANGES_REQUESTED').at(-1)?.feedback
    || project?.pendingOwnerFeedback?.feedback
    || '';
}

export function demoProductName(project) {
  const specName = specProductName(project?.council?.discovery?.spec);
  if (specName && specName !== 'Generated Application') return specName;
  if (isRecipeFixture(project)) return 'Recipe Box';
  return specName || 'Generated Application';
}

export function demoProductSummary(project) {
  const spec = project?.council?.discovery?.spec || {};
  return spec.productSummary
    || spec.product?.summary
    || (isRecipeFixture(project)
      ? 'Browse recipes, search, open details, save favorites, and plan the week.'
      : (project?.idea || 'A demo application for owner review.'));
}

export function demoOwnerJourneys(project) {
  if (isRecipeFixture(project)) return [...RECIPE_JOURNEYS];
  const fromSpec = flattenGuidance(project?.council?.discovery?.spec?.requirements)
    .filter(item => !/test|runtime verification|secrets in source|maintainable structure/i.test(item));
  if (fromSpec.length >= 3) return fromSpec.slice(0, 6);
  return [...GENERIC_JOURNEYS];
}

export function flattenGuidance(value) {
  if (Array.isArray(value)) return value.flatMap(item => flattenGuidance(item));
  if (value && typeof value === 'object') {
    if (value.title) return [String(value.title)];
    return Object.values(value).flatMap(item => flattenGuidance(item));
  }
  if (value == null || value === '') return [];
  return [String(value)];
}

export function demoRevisionOptions(project, version = 1) {
  const feedback = lastOwnerFeedback(project);
  return {
    version,
    feedback,
    compactHome: version > 1 && /busy|clutter|simple|fewer|spacious/i.test(feedback),
    largerImages: version > 1 && /larger|bigger|image/i.test(feedback)
  };
}

export function buildDemoAppFiles(project, { version } = {}) {
  const recipe = isRecipeFixture(project);
  const name = demoProductName(project);
  const summary = demoProductSummary(project);
  const deliveryVersion = Number(version || Math.max(1, ...(project?.deliveries || []).map(item => Number(item.version || 0)), 1));
  const revision = demoRevisionOptions(project, deliveryVersion);
  const config = {
    fixture: recipe ? 'recipe' : 'generic',
    name,
    summary,
    version: revision.version,
    feedback: revision.feedback || '',
    compactHome: revision.compactHome,
    largerImages: revision.largerImages,
    journeys: demoOwnerJourneys(project),
    items: recipe ? recipeCatalog() : genericCatalog(project, name)
  };
  return {
    'index.html': demoIndexHtml(config),
    'styles.css': demoStylesCss(config),
    'app.js': demoAppJs(),
    'README.md': demoReadme(config)
  };
}

export async function writeDemoAppFiles(dir, project, options = {}) {
  const files = buildDemoAppFiles(project, options);
  await fs.mkdir(dir, { recursive: true });
  const names = [];
  for (const [rel, contents] of Object.entries(files)) {
    await fs.writeFile(path.join(dir, rel), contents, 'utf8');
    names.push(rel);
  }
  return names;
}

function recipeCatalog() {
  return [
    { id: 'lemon-pasta', title: 'Lemon Pasta', time: '25 min', tags: ['dinner', 'pasta'], blurb: 'Bright lemon, garlic, and parmesan.', ingredients: ['320g spaghetti', '1 lemon', '2 garlic cloves', 'Parmesan', 'Olive oil'], steps: ['Boil pasta until al dente.', 'Warm garlic in olive oil.', 'Toss with lemon zest, juice, and cheese.'] },
    { id: 'herb-chicken', title: 'Herb Roast Chicken', time: '50 min', tags: ['dinner', 'protein'], blurb: 'Crisp skin with thyme and lemon.', ingredients: ['1 chicken', 'Thyme', 'Lemon', 'Salt'], steps: ['Season the chicken.', 'Roast at 220°C until juices run clear.', 'Rest 10 minutes before carving.'] },
    { id: 'berry-oats', title: 'Berry Overnight Oats', time: '10 min', tags: ['breakfast'], blurb: 'Make-ahead oats with yogurt and berries.', ingredients: ['Rolled oats', 'Milk', 'Yogurt', 'Berries'], steps: ['Mix oats, milk, and yogurt.', 'Chill overnight.', 'Top with berries.'] },
    { id: 'garden-salad', title: 'Garden Salad', time: '15 min', tags: ['lunch', 'salad'], blurb: 'Crunchy greens with a simple vinaigrette.', ingredients: ['Mixed greens', 'Cucumber', 'Tomato', 'Olive oil', 'Vinegar'], steps: ['Chop vegetables.', 'Whisk oil and vinegar.', 'Toss and serve.'] },
    { id: 'tomato-soup', title: 'Tomato Soup', time: '30 min', tags: ['lunch', 'soup'], blurb: 'Smooth tomato soup for cool evenings.', ingredients: ['Tomatoes', 'Onion', 'Garlic', 'Stock', 'Cream'], steps: ['Sweat onion and garlic.', 'Simmer tomatoes with stock.', 'Blend and finish with cream.'] },
    { id: 'choco-pots', title: 'Chocolate Pots', time: '20 min', tags: ['dessert'], blurb: 'Small dark-chocolate pots for sharing.', ingredients: ['Dark chocolate', 'Cream', 'Egg yolks', 'Sugar'], steps: ['Melt chocolate with cream.', 'Whisk in yolks and sugar.', 'Chill until set.'] }
  ];
}

function genericCatalog(project, name) {
  const journeys = demoOwnerJourneys(project);
  const seeds = journeys.length ? journeys : [`Explore ${name}`, `Save a favorite in ${name}`, `Plan a week with ${name}`];
  return seeds.slice(0, 6).map((title, index) => ({
    id: `item-${index + 1}`,
    title: String(title).replace(/\.$/, ''),
    time: `${10 + index * 5} min`,
    tags: ['demo', index % 2 ? 'featured' : 'core'],
    blurb: `Interactive demo card for ${name}.`,
    ingredients: ['Demo data only', 'No live backend'],
    steps: ['Open this item.', 'Save it to Favorites if you like.', 'Add it to this week\'s plan.']
  }));
}

function demoIndexHtml(config) {
  const payload = JSON.stringify(config).replace(/</g, '\\u003c');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${escapeHtml(config.name)}</title>
  <link rel="stylesheet" href="./styles.css">
</head>
<body data-app="demo" data-fixture="${escapeHtml(config.fixture)}" data-delivery-version="${escapeHtml(String(config.version))}" class="${config.compactHome ? 'compact' : ''} ${config.largerImages ? 'large-art' : ''}">
  <header class="top">
    <div>
      <p class="eyebrow">DEMO · MOCK</p>
      <h1>${escapeHtml(config.name)}</h1>
      <p class="lede">${escapeHtml(config.summary)}</p>
    </div>
    <div class="top-actions">
      <label class="search-wrap">Search
        <input id="search" type="search" placeholder="Search ${escapeHtml(config.fixture === 'recipe' ? 'recipes' : 'items')}" aria-label="Search">
      </label>
      <button id="show-favorites" class="secondary" type="button">Favorites</button>
      <button id="show-plan" class="secondary" type="button">Meal plan</button>
    </div>
  </header>
  <p id="revision-banner" class="banner" ${config.feedback ? '' : 'hidden'}>Updated after owner review (v${escapeHtml(String(config.version))})${config.feedback ? `: ${escapeHtml(config.feedback)}` : ''}</p>
  <main>
    <section>
      <div class="section-head">
        <h2 id="catalog-title">${config.fixture === 'recipe' ? 'Recipes' : 'Catalog'}</h2>
        <p id="catalog-count" class="meta"></p>
      </div>
      <div id="grid" class="grid"></div>
    </section>
    <section id="detail" class="detail" hidden></section>
    <section id="favorites-panel" class="panel" hidden>
      <h2>Favorites</h2>
      <ul id="favorites-list"></ul>
    </section>
    <section id="plan-panel" class="panel" hidden>
      <h2>Weekly meal plan</h2>
      <p class="meta">Select an item, then choose a day.</p>
      <div id="plan-days" class="plan"></div>
    </section>
  </main>
  <footer>
    <p>${escapeHtml(DEMO_APP_DISCLAIMER)}</p>
  </footer>
  <script>window.ADP_DEMO = ${payload};</script>
  <script src="./app.js"></script>
</body>
</html>
`;
}

function demoStylesCss() {
  return `:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#171713;background:#f5f2e9}
*{box-sizing:border-box}body{margin:0}
.top,main,footer{max-width:980px;margin:auto;padding:28px 20px}
.top{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}
.eyebrow{letter-spacing:.16em;font-size:12px;font-weight:800;color:#8b4a32}
h1{font-family:Georgia,serif;font-size:clamp(32px,5vw,52px);font-weight:500;margin:.15em 0}
.lede,.meta{color:#67645d;line-height:1.55}
.top-actions{display:grid;gap:8px;min-width:220px}
.search-wrap{display:grid;gap:6px;font-weight:800;font-size:12px}
input,button{font:inherit}
input{border:1px solid #ccc1b2;border-radius:12px;padding:12px}
button{border:0;border-radius:12px;padding:11px 16px;background:#a45237;color:#fff;font-weight:800;cursor:pointer}
button.secondary{background:transparent;color:#5b554c;border:1px solid #d5c8b8}
.banner{max-width:980px;margin:0 auto;padding:10px 20px;color:#8b4a32;font-weight:700}
.section-head{display:flex;justify-content:space-between;align-items:baseline}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}
body.compact .grid{gap:22px}
.card{background:#fffdfa;border:1px solid #ded7cb;border-radius:18px;overflow:hidden;box-shadow:0 10px 24px #4a3f3218;cursor:pointer}
.art{height:110px;background:linear-gradient(135deg,#e7d3c0,#c97858 55%,#8b4a32)}
body.large-art .art{height:180px}
body.compact .card:nth-child(n+4){display:none}
.card h3{margin:12px 16px 4px;font-family:Georgia,serif}
.card p{margin:0 16px 14px;color:#716c63;font-size:14px}
.detail,.panel{background:#fffdfa;border:1px solid #ded7cb;border-radius:18px;padding:20px;margin-top:18px}
.detail h2{margin-top:0;font-family:Georgia,serif}
.plan{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px}
.day{border:1px dashed #d5c8b8;border-radius:12px;padding:12px;min-height:88px}
.day strong{display:block;margin-bottom:6px}
.fav{margin-top:12px}
footer{color:#716c63;font-size:13px;line-height:1.5}
.selected{outline:3px solid #a45237}
`;
}

function demoAppJs() {
  return `const cfg = window.ADP_DEMO || { items: [], name: 'Demo' };
const storageKey = (name) => 'adp-demo:' + cfg.name + ':' + name;
const items = cfg.items || [];
let selectedId = items[0]?.id || null;
let filter = '';
let favoritesOnly = false;
const favorites = new Set(JSON.parse(localStorage.getItem(storageKey('favorites')) || '[]'));
const plan = JSON.parse(localStorage.getItem(storageKey('plan')) || '{}');
const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

const grid = document.getElementById('grid');
const detail = document.getElementById('detail');
const search = document.getElementById('search');
const favBtn = document.getElementById('show-favorites');
const planBtn = document.getElementById('show-plan');
const favPanel = document.getElementById('favorites-panel');
const planPanel = document.getElementById('plan-panel');
const favList = document.getElementById('favorites-list');
const planDays = document.getElementById('plan-days');
const count = document.getElementById('catalog-count');

function visibleItems() {
  const q = filter.trim().toLowerCase();
  return items.filter((item) => {
    if (favoritesOnly && !favorites.has(item.id)) return false;
    if (!q) return true;
    return [item.title, item.blurb, ...(item.tags || [])].join(' ').toLowerCase().includes(q);
  });
}

function renderGrid() {
  const shown = visibleItems();
  count.textContent = shown.length + ' shown';
  grid.innerHTML = shown.map((item) => \`<article class="card\${item.id === selectedId ? ' selected' : ''}" data-id="\${item.id}"><div class="art" aria-hidden="true"></div><h3>\${esc(item.title)}</h3><p>\${esc(item.time)} · \${esc((item.tags || []).join(', '))}</p></article>\`).join('') || '<p class="meta">No matches.</p>';
}

function renderDetail(item) {
  if (!item) { detail.hidden = true; return; }
  detail.hidden = false;
  const saved = favorites.has(item.id);
  detail.innerHTML = \`<h2>\${esc(item.title)}</h2><p class="meta">\${esc(item.blurb)}</p><p><strong>Time:</strong> \${esc(item.time)}</p><h3>Ingredients</h3><ul>\${(item.ingredients || []).map((row) => \`<li>\${esc(row)}</li>\`).join('')}</ul><h3>Steps</h3><ol>\${(item.steps || []).map((row) => \`<li>\${esc(row)}</li>\`).join('')}</ol><button class="fav" id="toggle-fav" type="button">\${saved ? 'Remove from Favorites' : 'Save to Favorites'}</button>\`;
  document.getElementById('toggle-fav').onclick = () => {
    if (favorites.has(item.id)) favorites.delete(item.id); else favorites.add(item.id);
    localStorage.setItem(storageKey('favorites'), JSON.stringify([...favorites]));
    renderAll();
  };
}

function renderFavorites() {
  const rows = items.filter((item) => favorites.has(item.id));
  favList.innerHTML = rows.map((item) => \`<li>\${esc(item.title)}</li>\`).join('') || '<li>No favorites yet.</li>';
}

function renderPlan() {
  planDays.innerHTML = days.map((day) => {
    const id = plan[day];
    const item = items.find((row) => row.id === id);
    return \`<button class="day" data-day="\${day}" type="button"><strong>\${day}</strong><span>\${item ? esc(item.title) : 'Add item'}</span></button>\`;
  }).join('');
}

function renderAll() {
  renderGrid();
  renderDetail(items.find((item) => item.id === selectedId));
  renderFavorites();
  renderPlan();
}

grid.addEventListener('click', (event) => {
  const card = event.target.closest('[data-id]');
  if (!card) return;
  selectedId = card.dataset.id;
  favPanel.hidden = true;
  planPanel.hidden = true;
  renderAll();
});

search.addEventListener('input', () => {
  filter = search.value;
  favoritesOnly = false;
  renderAll();
});

favBtn.addEventListener('click', () => {
  favoritesOnly = !favoritesOnly;
  favPanel.hidden = !favoritesOnly;
  planPanel.hidden = true;
  favBtn.textContent = favoritesOnly ? 'All items' : 'Favorites';
  renderAll();
});

planBtn.addEventListener('click', () => {
  planPanel.hidden = !planPanel.hidden;
  favPanel.hidden = true;
  renderAll();
});

planDays.addEventListener('click', (event) => {
  const day = event.target.closest('[data-day]')?.dataset.day;
  if (!day || !selectedId) return;
  if (plan[day] === selectedId) delete plan[day];
  else plan[day] = selectedId;
  localStorage.setItem(storageKey('plan'), JSON.stringify(plan));
  renderAll();
});

function esc(value) {
  return String(value || '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

renderAll();
`;
}

function demoReadme(config) {
  return `# ${config.name}

${config.summary}

${DEMO_APP_DISCLAIMER}

## Try this
${(config.journeys || []).map(item => `- ${item}`).join('\n')}

Open \`index.html\` in a browser, or use **Open App** from the owner dashboard.
`;
}

function escapeHtml(value) {
  return String(value || '').replace(/[&<>"']/g, char => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;'
  }[char]));
}
