export const SecurityProfile = Object.freeze({
  DEVELOPMENT: 'DEVELOPMENT',
  STANDARD: 'STANDARD',
  HARDENED: 'HARDENED'
});

export const SandboxMode = Object.freeze({
  CONTAINER_HARDENED: 'CONTAINER_HARDENED',
  LOCAL_DEVELOPMENT_UNSAFE: 'LOCAL_DEVELOPMENT_UNSAFE',
  MOCK: 'MOCK'
});

export const SecretClass = Object.freeze({
  CONTROL_PLANE_SECRET: 'CONTROL_PLANE_SECRET',
  PROJECT_BUILD_SECRET: 'PROJECT_BUILD_SECRET',
  PROJECT_RUNTIME_SECRET: 'PROJECT_RUNTIME_SECRET',
  PROJECT_TEST_SECRET: 'PROJECT_TEST_SECRET',
  EXTERNAL_SERVICE_SECRET: 'EXTERNAL_SERVICE_SECRET',
  OWNER_AUTH_SECRET: 'OWNER_AUTH_SECRET'
});

export const SecurityRole = Object.freeze({
  OWNER: 'OWNER',
  WORKER: 'WORKER',
  SYSTEM: 'SYSTEM'
});

export const SecurityEventType = Object.freeze({
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  AUTHZ_DENIED: 'AUTHZ_DENIED',
  SANDBOX_STARTED: 'SANDBOX_STARTED',
  SANDBOX_VIOLATION: 'SANDBOX_VIOLATION',
  SANDBOX_RESOURCE_LIMIT: 'SANDBOX_RESOURCE_LIMIT',
  SECRET_ISSUED: 'SECRET_ISSUED',
  SECRET_REVOKED: 'SECRET_REVOKED',
  SECRET_ACCESS_DENIED: 'SECRET_ACCESS_DENIED',
  SECRET_DETECTED_IN_SOURCE: 'SECRET_DETECTED_IN_SOURCE',
  NETWORK_POLICY_DENIED: 'NETWORK_POLICY_DENIED',
  PROMPT_INJECTION_DETECTED: 'PROMPT_INJECTION_DETECTED',
  PROTECTED_PATH_DENIED: 'PROTECTED_PATH_DENIED'
});

export const SecurityFindingKind = Object.freeze({
  PROJECT_SECURITY_DEFECT: 'PROJECT_SECURITY_DEFECT',
  INFRASTRUCTURE_SECURITY_UNAVAILABLE: 'INFRASTRUCTURE_SECURITY_UNAVAILABLE',
  SOURCE_SECRET: 'SOURCE_SECRET',
  SANDBOX_VIOLATION: 'SANDBOX_VIOLATION',
  DEPENDENCY: 'DEPENDENCY',
  PROMPT_INJECTION: 'PROMPT_INJECTION'
});

export const ScreenshotClass = Object.freeze({
  PUBLIC_TEST_DATA: 'PUBLIC_TEST_DATA',
  SYNTHETIC: 'SYNTHETIC',
  SENSITIVE_TEST_DATA: 'SENSITIVE_TEST_DATA',
  EXTERNAL_REVIEW_PROHIBITED: 'EXTERNAL_REVIEW_PROHIBITED'
});

export const InstructionPrecedence = Object.freeze([
  'PLATFORM_SECURITY_POLICY',
  'OWNER_PRODUCT_INTENT',
  'COUNCIL_AUTHORITATIVE_SPEC',
  'CURSOR_TASK',
  'REPOSITORY_CONTENT'
]);

export const CONTROL_PLANE_SECRET_NAMES = Object.freeze([
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'GEMINI_API_KEY',
  'XAI_API_KEY',
  'CURSOR_API_KEY',
  'CURSOR_CLOUD_API_KEY',
  'CURSOR_AUTH_TOKEN',
  'DATABASE_URL',
  'TEST_DATABASE_URL',
  'SECRET_MASTER_KEY',
  'VAULT_TOKEN',
  'VAULT_TOKEN_FILE',
  'OWNER_TOKEN_BOOTSTRAP',
  'WORKER_TOKEN',
  'SECRET_BROKER_TOKEN',
  'CHAIR_PROVIDER'
]);
